# docker-compose.yml

version: '3.8'

services:
  backend:
    container_name: cassia-api-backend-qa
    image: cassia-api-backend-qa
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - api_network
networks:
  api_network:
    driver: host
    external: true
    name: api_backend_qa_network
# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]
