# docker-compose.yml

version: '3.8'

services:
  backend:
    container_name: cassia-api-backend-qa
    image: cassia-api-backend-qa
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000

    networks:
      default:
        # Use a custom driver
        driver: api-qa-driver

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]
